name: BendingLWC
version: '${version}'
main: me.moros.bending.paper.BendingLWC
author: Moros
description: Bending - LWC integration
website: https://github.com/PrimordialMoros/bending-protections
api-version: '${mcVersion}'
dependencies:
  server:
    Bending:
      load: BEFORE
      required: true
    LWC:
      load: BEFORE
      required: true
