name: BendingBolt
version: '${version}'
main: me.moros.bending.paper.BendingBolt
author: Moros
description: Bending - Bolt integration
website: https://github.com/PrimordialMoros/bending-protections
api-version: '${mcVersion}'
dependencies:
  server:
    Bending:
      load: BEFORE
      required: true
    Bolt:
      load: BEFORE
      required: true
